name: Publish npm Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.16.0'
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm install
    
    - name: Update npm version
      run: npm version patch 

    - name: Publish to npm
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
